// Storage adapter: plain JSON file + local uploads folder in dev,
// Netlify Blobs in production (Netlify functions have a read-only filesystem).
import { promises as fs } from "fs";
import path from "path";
import type { SiteContent } from "./types";
import { defaultContent } from "./seed";

const DATA_DIR = path.join(process.cwd(), "data");
const CONTENT_FILE = path.join(DATA_DIR, "content.json");
const UPLOADS_DIR = path.join(DATA_DIR, "uploads");

const CONTENT_KEY = "site-content";

function onNetlify(): boolean {
  return process.env.NETLIFY === "true" || !!process.env.NETLIFY_BLOBS_CONTEXT;
}

async function blobStore(name: string) {
  const { getStore } = await import("@netlify/blobs");
  return getStore({ name, consistency: "strong" });
}

/**
 * Content saved before a feature existed won't have its field. Fill those in
 * from the seed so an older saved blob keeps working after a deploy.
 */
function withDefaults(content: SiteContent): SiteContent {
  if (content.exhibitions === undefined) {
    return { ...content, exhibitions: defaultContent.exhibitions };
  }
  return content;
}

export async function getContent(): Promise<SiteContent> {
  if (onNetlify()) {
    const store = await blobStore("content");
    const data = (await store.get(CONTENT_KEY, { type: "json" })) as SiteContent | null;
    return withDefaults(data ?? defaultContent);
  }
  try {
    const raw = await fs.readFile(CONTENT_FILE, "utf-8");
    return withDefaults(JSON.parse(raw) as SiteContent);
  } catch {
    await saveContent(defaultContent);
    return defaultContent;
  }
}

export async function saveContent(content: SiteContent): Promise<void> {
  if (onNetlify()) {
    const store = await blobStore("content");
    await store.setJSON(CONTENT_KEY, content);
    return;
  }
  await fs.mkdir(DATA_DIR, { recursive: true });
  await fs.writeFile(CONTENT_FILE, JSON.stringify(content, null, 2), "utf-8");
}

export async function saveImage(key: string, data: ArrayBuffer): Promise<void> {
  if (onNetlify()) {
    const store = await blobStore("images");
    await store.set(key, data);
    return;
  }
  await fs.mkdir(UPLOADS_DIR, { recursive: true });
  await fs.writeFile(path.join(UPLOADS_DIR, key), Buffer.from(data));
}

export async function getImage(key: string): Promise<ArrayBuffer | null> {
  // keys are generated by the upload route; reject anything path-like
  if (!/^[\w.-]+$/.test(key)) return null;
  if (onNetlify()) {
    const store = await blobStore("images");
    return await store.get(key, { type: "arrayBuffer" });
  }
  try {
    const buf = await fs.readFile(path.join(UPLOADS_DIR, key));
    return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
  } catch {
    return null;
  }
}

export function imageContentType(key: string): string {
  const ext = key.split(".").pop()?.toLowerCase();
  switch (ext) {
    case "jpg":
    case "jpeg":
      return "image/jpeg";
    case "png":
      return "image/png";
    case "webp":
      return "image/webp";
    case "gif":
      return "image/gif";
    case "avif":
      return "image/avif";
    default:
      return "application/octet-stream";
  }
}
